name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    services:
      db:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          SA_PASSWORD: ${{ secrets.DB_PASSWORD }}
          ACCEPT_EULA: 'Y'
        ports:
          - 1433:1433
        options: >-
          --health-cmd "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $SA_PASSWORD -Q 'SELECT 1'" 
          --health-interval 10s 
          --health-start-period 30s 
          --health-timeout 5s 
          --health-retries 3

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20.15.1'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Set up database schema
        run: |
          sudo apt-get install -y mssql-tools
          sleep 60 # Wait for MSSQL to be ready
          /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${{ secrets.DB_PASSWORD }} -d master -i schema.sql
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Run Playwright tests
        run: npx playwright test
        env:
          DB_HOST: localhost
          DB_USER: sa
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: jokesdb

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
